---
title: "Schule-Block-Zuordnung"
author: "idalab GmbH"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output: pdf_document
classoption: a4paper
params:
  map: ""
  units: ""
  entities: ""
  entity_stats: ""
  assignment: "" 
---

```{r libs, include=FALSE, message=FALSE, warning=FALSE, error=FALSE}
```

## Kartendarstellung der Einzugsbereiche

```{r map, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE, fig.align='center', out.extra='keepaspectratio', fig.height=8.5}
tmp_units = broom::tidy(params$units, region = 'unit_id') %>%
  dplyr::inner_join(params$units@data, by = c("id" = "unit_id")) %>%
  dplyr::select(entity_id, group, long, lat)
tmp_shown = tmp_units %>%
  dplyr::filter(entity_id != "__NONE_SELECTED__")
tmp_unassigned = tmp_units %>%
  dplyr::filter(entity_id == "__NONE_SELECTED__")
tmp_entities <- as.data.frame(params$entities) %>%
  dplyr::select(entity_id, long = coords.x1, lat = coords.x2)

ggmap::ggmap(params$map) +
  ggplot2::geom_polygon(mapping = aes(x = long, y = lat, group = group, fill = entity_id),
                        data = tmp_shown) +
  ggplot2::geom_polygon(mapping = aes(x = long, y = lat, group = group),
                        data = tmp_unassigned,
                        fill = "black", alpha = 1/4) +
  ggplot2::geom_point(mapping = aes(x = long, y = lat),
                      data = tmp_entities,
                      size = 1) +
  ggplot2::geom_text(mapping = aes(x = long, y = lat, label = entity_id),
                     data = tmp_entities,
                     size = 3,
                     nudge_x = 0.002,
                     hjust = 0) +
  ggplot2::coord_map(xlim = params$units@bbox["x",] + c(-0.01, 0.01),
                     ylim = params$units@bbox["y",] + c(-0.01, 0.01)) +
  ggplot2::scale_fill_discrete() +
  ggplot2::theme(
    axis.line=element_blank(),
    axis.text.x=element_blank(),
    axis.text.y=element_blank(),
    axis.ticks=element_blank(),
    axis.title.x=element_blank(),
    axis.title.y=element_blank(),
    legend.position="none"
  )
```

## Statistik zu den Einzugsbereichen

```{r stats, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
knitr::kable(params$entity_stats)
```

```{r pretty_table, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
```

## Schulen-Blöcke-Zuordnung

```{r solution, results='asis', echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
entity_units <- params$assignment %>%
  dplyr::select(entity_id, unit_id) %>%
  dplyr::group_by(entity_id) %>%
  dplyr::summarise(unit_ids = paste(unit_id, sep = "", collapse = ", "))

for (i in 1:nrow(entity_units)) {
  cat("**", entity_units[[i, "entity_id"]], ":**\n", sep = "")
  cat(entity_units[[i, "unit_ids"]], "\n\n", sep = "")
}
```
