---
title: "Schule-Block-Zuordnung"
author: "idalab GmbH"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output: pdf_document
header-includes:
  - \usepackage{booktabs}
  - \usepackage{xcolor}
  - \usepackage{longtable}
  - \definecolor{BrewerRed}{HTML}{E41A1C}
classoption: a4paper
params:
  map: ""
  addresses: ""
  units: ""
  entities: ""
  weights: ""
  colors: ""
  NO_ASSIGNMENT: ""
  optimizable_units: ""
  crit_dist: 2000
  min_util: 0.9
  max_util: 1.1
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE, error=FALSE}
source('../io.R')
source('../addresslist.R')
```

```{r libs, include=FALSE, message=FALSE, warning=FALSE, error=FALSE}
percent <- function(x, digits = 2, format = "f", ...) {
  paste0(formatC(100 * x, format = format, digits = digits, ...), "%")
}
```

## Kartendarstellung der Einzugsbereiche

```{r map, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE, fig.align='center', out.extra='keepaspectratio', fig.height=8}
tmp_units = broom::tidy(params$units, region = 'unit_id') %>%
  dplyr::inner_join(params$units@data, by = c("id" = "unit_id")) %>%
  dplyr::select(id, entity_id, group, long, lat) %>%
  dplyr::mutate(optim = id %in% params$optimizable_units)
tmp_shown = tmp_units %>%
  dplyr::filter(optim)
tmp_unassigned = tmp_units %>%
  dplyr::filter(!optim)
tmp_entities <- as.data.frame(params$entities) %>%
  dplyr::select(entity_id, long = coords.x1, lat = coords.x2)

ggmap::ggmap(params$map, extent = "device", legend = "none") +
  ggplot2::geom_polygon(mapping = ggplot2::aes(x = long, y = lat, group = group, fill = entity_id),
                        data = tmp_shown) +
  ggplot2::geom_polygon(mapping = ggplot2::aes(x = long, y = lat, group = group),
                        data = tmp_unassigned,
                        fill = "black", alpha = 1/4) +
  ggplot2::geom_point(mapping = ggplot2::aes(x = long, y = lat),
                      data = tmp_entities,
                      size = 1) +
  ggrepel::geom_text_repel(mapping = ggplot2::aes(x = long, y = lat, label = entity_id),
                     data = tmp_entities,
                     size = 3) +
  ggplot2::coord_map(xlim = params$units@bbox["x",] + c(-0.01, 0.01),
                     ylim = params$units@bbox["y",] + c(-0.01, 0.01)) +
  ggplot2::scale_fill_manual(values = params$colors) +
  ggplot2::theme(legend.position = "none")
```

## Statistik zu den Einzugsbereichen

```{r entity_stats, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
table_data = generate_tbl(params$units, params$entities, params$weights,
                          params$NO_ASSIGNMENT) %>%
  dplyr::select(entity_id, capacity, pop, utilization,
                sgbIIu65, avg_dist, max_dist)

header <- c("Schule",
            "Kapazität",
            "Kinder",
            "Auslastung",
            "SGBII(u.65)",
            "Weg (Ø)",
            "Weg (max)")
```

```{r, include=FALSE}
markup = function(elem) {
  paste0("\\textcolor{BrewerRed}{\\bf ", elem, "}")
}

tex_percent <- function(x, digits = 2, format = "f", ...) {
  paste0(formatC(100 * x, format = format, digits = digits, ...), "\\%")
}
```

```{r entity-table, results='asis', echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
tmp_tbl = table_data %>%
  dplyr::mutate(avg_dist = as.integer(round(avg_dist)),
                max_dist = as.integer(round(max_dist))) %>%
  dplyr::mutate(sgbIIu65 = tex_percent(sgbIIu65, digits = 1),
                utilization = ifelse(
                  utilization < params$min_util | utilization > params$max_util,
                  markup(tex_percent(utilization, digits = 1)),
                  tex_percent(utilization, digits = 1)),
                avg_dist = ifelse(avg_dist >= params$crit_dist,
                                  markup(avg_dist), avg_dist),
                max_dist = ifelse(max_dist >= params$crit_dist,
                                  markup(max_dist), max_dist))
tbl_summary = table_data %>% summarise(
  entity_id="Gesamt",
  sum_capacity=sum(capacity),
  sum_pop=sum(pop),
  utilization=tex_percent(sum_pop/sum_capacity),
  sgbIIu65='-',
  avg_dist=sum(pop*avg_dist)/sum(pop),
  max_dist=as.integer(round(max(max_dist)))
)
colnames(tbl_summary) = colnames(tmp_tbl)
tmp_tbl = rbind(tmp_tbl, tbl_summary)

colnames(tmp_tbl) = header
print(xtable::xtable(tmp_tbl, digits = 1, align = c("l", "l", rep("r", times = 6))),
      booktabs = TRUE, include.rownames = FALSE, comment = FALSE,
      hline.after = c(-1, 0, nrow(tmp_tbl) - 1, nrow(tmp_tbl)),
      sanitize.text.function = identity)
```

## Adressliste

```{r addresses, results='asis', echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
table = cbind(
  as.data.frame(addresses),
  over(addresses, generate_spatial_df(units, entities, weights, NO_ASSIGNMENT))
  ) %>%
  group_by(entity_id) %>%
  do(data.frame(addresses=to_addresslist(.))) %>%
  arrange(addresses) %>%
  select(Straße=addresses, Schule=entity_id)

print(
  xtable::xtable(table[!is.na(table$Schule),], align='lp{12cm}r'),
  include.rownames = FALSE, comment = FALSE,
  tabular.environment="longtable", floating=FALSE
)
```

### Ohne Zuordnung

```{r addresses-na, results='asis', echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
print(
  xtable::xtable(table[is.na(table$Schule), c('Straße')], align='lp{14cm}'),
  include.rownames = FALSE, comment = FALSE,
  tabular.environment="longtable", floating=FALSE
)
```