---
title: "Schule-Block-Zuordnung"
author: "idalab GmbH"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  pdf_document
header-includes:
  - \usepackage{booktabs}
  - \usepackage{siunitx}
  - \usepackage{xcolor}
  - \definecolor{BrewerGreen}{HTML}{4DAF4A}
  - \definecolor{BrewerRed}{HTML}{E41A1C}
classoption: a4paper
params:
  map: ""
  units: ""
  entities: ""
  weights: ""
  colors: ""
  NO_ASSIGNMENT: ""
  optimizable_units: ""
---
```{r libs, include=FALSE, message=FALSE, warning=FALSE, error=FALSE}
percent <- function(x, digits = 2, format = "f", ...) {
  paste0(formatC(100 * x, format = format, digits = digits, ...), "%")
}
```

## Statistik zu den Einzugsbereichen

```{r entity_stats, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
table_data = params$units %>%
  as.data.frame() %>%
  dplyr::filter(entity_id != params$NO_ASSIGNMENT) %>%
  dplyr::left_join(params$weights, by=c('unit_id', 'entity_id')) %>%
  dplyr::group_by(entity_id) %>%
  dplyr::summarise(
    num_units = n(),
    pop = sum(population, na.rm = TRUE),
    sgbIIu65 = sum(population * sgbIIu65, na.rm = TRUE) / pop,
    avg_dist = sum(population * avg, na.rm = TRUE) / pop,
    max_dist = max(max, na.rm = TRUE)
  ) %>%
  dplyr::left_join(params$entities %>%
                     as.data.frame() %>%
                     dplyr::select(entity_id, capacity),
                   by = 'entity_id') %>%
  dplyr::mutate(utilization = pop / capacity) %>%
  dplyr::select(entity_id, capacity, pop, utilization,
                sgbIIu65, avg_dist, max_dist)

header <- c("Schule",
            "Kapazität",
            "Kinder",
            "Auslastung",
            "SGBII(u.65)",
            "Weg (Ø)",
            "Weg (max)")
```

```{r table-kable, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
table_data %>%
  dplyr::mutate(sgbIIu65 = percent(sgbIIu65, digits = 1),
                utilization = percent(utilization, digits = 1)) %>%
  knitr::kable(digits = 1, col.names = header, caption = "kable")
```

```{r, include=FALSE}
# http://stackoverflow.com/a/37122306
format_color = function(x, color) {
  output = knitr::opts_knit$get("rmarkdown.pandoc.to")
  if (output == 'latex')
    paste0("\\textcolor{", color, "}{", x, "}")
  else if(output == 'html')
    paste0('<font color="', color, '">', x, '</font>')
  else
    x
}

format_box = function(x, color, max) {
  output = knitr::opts_knit$get("rmarkdown.pandoc.to")
  if (output == 'latex')
    paste0("\\colorbox{", color, "!", round(x / max * 100),
           "}{", round(x, digits = 1), "}")
  else
    x
}

tex_percent <- function(x, digits = 2, format = "f", ...) {
  paste0(formatC(100 * x, format = format, digits = digits, ...), "\\%")
}
```

```{r table-xtable, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE, results='asis'}
max_avg = max(table_data$avg_dist, na.rm = TRUE)
max_max = max(table_data$max_dist, na.rm = TRUE)
tmp_tbl = table_data %>%
  dplyr::mutate(sgbIIu65 = tex_percent(sgbIIu65, digits = 1),
                utilization = ifelse(
                  utilization <= 1,
                  format_color(tex_percent(utilization, digits = 1), "BrewerGreen"),
                  format_color(tex_percent(utilization, digits = 1), "BrewerRed")),
                avg_dist = format_box(avg_dist, "blue", max_avg),
                max_dist = format_box(max_dist, "blue", max_max))
colnames(tmp_tbl) = header
print(xtable::xtable(tmp_tbl, caption = 'xtable', digits = 1,
                     align = c("l", "l", rep("r", times = 6))),
      booktabs = TRUE, include.rownames = FALSE, comment = FALSE,
      caption.placement = "top", sanitize.text.function = identity)
```

```{r table-pander}

```

```{r table-irutils}
```



